### ISSUE TITLE
uneccessarry directories : [*/web/**/quizzer], [*/web/**/employee]

### ISSUE THREAD

**Issue by regisrex** [Mutesa-Cedric/Fullstack-typesafe-monorepo#1]
I think those folder aren't common for all projects so they must 
be removed : 
```
\apps\web\src\screens\quizzer
\apps\web\src\screens\quizzer
```

**Comment by Mutesa-Cedric** [comment]
this issue was fixed in this commit : https://github.com/Mutesa-Cedric/Fullstack-typesafe-monorepo/commit/5551400072dc15be9b5ed155231b92eb7886dc1b

thank you!
